version: '3'
services:
  flask:
    build: .
    volumes:
      - ./app.py:/src/app.py
    environment:
      - FLASK_APP=/src/app.py
  nginx:
    image: nginx:latest
    ports:
      - "2000:80"
    volumes:
      - ./demo.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
